import type { ConversionCategoryDto } from "../dto";
const units = (entries: Array<[string, string, string, number]>) =>
  entries.map(([id, label, symbol, factor]) => ({ id, label, symbol, factor }));
const standard = (
  id: string,
  name: string,
  description: string,
  icon: string,
  values: Array<[string, string, string, number]>,
): ConversionCategoryDto => ({
  id,
  name,
  description,
  icon,
  units: units(values),
});
export const conversionCategories: ConversionCategoryDto[] = [
  standard("length", "Length", "Distance and dimensions", "↔", [
    ["mm", "Millimeter", "mm", 0.001],
    ["cm", "Centimeter", "cm", 0.01],
    ["m", "Meter", "m", 1],
    ["km", "Kilometer", "km", 1000],
    ["in", "Inch", "in", 0.0254],
    ["ft", "Foot", "ft", 0.3048],
    ["yd", "Yard", "yd", 0.9144],
    ["mi", "Mile", "mi", 1609.344],
  ]),
  standard("mass", "Mass", "Weight and mass", "⚖", [
    ["mg", "Milligram", "mg", 0.000001],
    ["g", "Gram", "g", 0.001],
    ["kg", "Kilogram", "kg", 1],
    ["t", "Metric ton", "t", 1000],
    ["oz", "Ounce", "oz", 0.028349523125],
    ["lb", "Pound", "lb", 0.45359237],
    ["ton", "US ton", "ton", 907.18474],
  ]),
  {
    id: "temperature",
    name: "Temperature",
    description: "Heat and climate",
    icon: "◌",
    units: [
      { id: "c", label: "Celsius", symbol: "°C" },
      { id: "f", label: "Fahrenheit", symbol: "°F" },
      { id: "k", label: "Kelvin", symbol: "K" },
    ],
  },
  standard("area", "Area", "Surface measurements", "□", [
    ["m2", "Square meter", "m²", 1],
    ["km2", "Square kilometer", "km²", 1e6],
    ["ha", "Hectare", "ha", 1e4],
    ["ft2", "Square foot", "ft²", 0.09290304],
    ["yd2", "Square yard", "yd²", 0.83612736],
    ["acre", "Acre", "ac", 4046.8564224],
  ]),
  standard("volume", "Volume", "Capacity and liquid", "▱", [
    ["ml", "Milliliter", "mL", 0.001],
    ["l", "Liter", "L", 1],
    ["m3", "Cubic meter", "m³", 1000],
    ["tsp", "Teaspoon", "tsp", 0.00492892159375],
    ["tbsp", "Tablespoon", "tbsp", 0.01478676478125],
    ["cup", "US cup", "cup", 0.2365882365],
    ["gal", "US gallon", "gal", 3.785411784],
    ["ft3", "Cubic foot", "ft³", 28.316846592],
  ]),
  standard("speed", "Speed", "Velocity and travel", "➜", [
    ["ms", "Meters per second", "m/s", 1],
    ["kph", "Kilometers per hour", "km/h", 0.2777777778],
    ["mph", "Miles per hour", "mph", 0.44704],
    ["knot", "Knot", "kn", 0.5144444444],
  ]),
  standard("time", "Time", "Durations and intervals", "◷", [
    ["ms", "Millisecond", "ms", 0.001],
    ["s", "Second", "s", 1],
    ["min", "Minute", "min", 60],
    ["h", "Hour", "h", 3600],
    ["day", "Day", "d", 86400],
    ["week", "Week", "wk", 604800],
    ["month", "Month (30 days)", "mo", 2592000],
    ["year", "Year (365 days)", "yr", 31536000],
  ]),
  standard("pressure", "Pressure", "Force per area", "◒", [
    ["pa", "Pascal", "Pa", 1],
    ["kpa", "Kilopascal", "kPa", 1000],
    ["bar", "Bar", "bar", 100000],
    ["atm", "Atmosphere", "atm", 101325],
    ["psi", "Pounds per square inch", "psi", 6894.757293],
    ["torr", "Torr", "Torr", 133.322368],
  ]),
  standard("energy", "Energy", "Work and heat energy", "ϟ", [
    ["j", "Joule", "J", 1],
    ["kj", "Kilojoule", "kJ", 1000],
    ["cal", "Calorie", "cal", 4.184],
    ["kcal", "Kilocalorie", "kcal", 4184],
    ["wh", "Watt-hour", "Wh", 3600],
    ["kwh", "Kilowatt-hour", "kWh", 3.6e6],
    ["btu", "BTU", "BTU", 1055.05585262],
  ]),
  standard("power", "Power", "Rate of energy use", "⚡", [
    ["w", "Watt", "W", 1],
    ["kw", "Kilowatt", "kW", 1000],
    ["hp", "Horsepower", "hp", 745.699872],
  ]),
  standard("force", "Force", "Push and pull", "↗", [
    ["n", "Newton", "N", 1],
    ["kn", "Kilonewton", "kN", 1000],
    ["lbf", "Pound-force", "lbf", 4.4482216153],
    ["dyne", "Dyne", "dyn", 0.00001],
  ]),
  standard("density", "Density", "Mass by volume", "◫", [
    ["kgm3", "Kilogram per cubic meter", "kg/m³", 1],
    ["gcm3", "Gram per cubic centimeter", "g/cm³", 1000],
    ["lbft3", "Pound per cubic foot", "lb/ft³", 16.01846337],
  ]),
  standard("frequency", "Frequency", "Cycles per second", "〰", [
    ["hz", "Hertz", "Hz", 1],
    ["khz", "Kilohertz", "kHz", 1000],
    ["mhz", "Megahertz", "MHz", 1e6],
    ["ghz", "Gigahertz", "GHz", 1e9],
  ]),
  standard("angle", "Angle", "Rotation and direction", "∠", [
    ["deg", "Degree", "°", 1],
    ["rad", "Radian", "rad", 57.2957795131],
    ["gon", "Gradian", "gon", 0.9],
  ]),
  standard("data", "Data", "Digital storage", "▣", [
    ["bit", "Bit", "b", 0.125],
    ["byte", "Byte", "B", 1],
    ["kb", "Kilobyte", "KB", 1024],
    ["mb", "Megabyte", "MB", 1048576],
    ["gb", "Gigabyte", "GB", 1073741824],
    ["tb", "Terabyte", "TB", 1099511627776],
  ]),
  standard("current", "Electric current", "Electrical charge flow", "⌁", [
    ["ma", "Milliampere", "mA", 0.001],
    ["a", "Ampere", "A", 1],
  ]),
  standard("voltage", "Voltage", "Electrical potential", "⌇", [
    ["mv", "Millivolt", "mV", 0.001],
    ["v", "Volt", "V", 1],
    ["kv", "Kilovolt", "kV", 1000],
  ]),
  standard("resistance", "Resistance", "Electrical resistance", "Ω", [
    ["ohm", "Ohm", "Ω", 1],
    ["kohm", "Kiloohm", "kΩ", 1000],
    ["mohm", "Megaohm", "MΩ", 1e6],
  ]),
  standard("capacitance", "Capacitance", "Electrical charge storage", "▰", [
    ["f", "Farad", "F", 1],
    ["uf", "Microfarad", "µF", 1e-6],
    ["nf", "Nanofarad", "nF", 1e-9],
    ["pf", "Picofarad", "pF", 1e-12],
  ]),
  standard("inductance", "Inductance", "Magnetic energy storage", "⌬", [
    ["h", "Henry", "H", 1],
    ["mh", "Millihenry", "mH", 0.001],
    ["uh", "Microhenry", "µH", 1e-6],
  ]),
  {
    id: "currency",
    name: "Currency",
    description: "Live exchange rates",
    icon: "$",
    units: [],
    isDynamic: true,
  },
];
